cc_library(
    name = "kube",
    srcs = [
        "_config.hpp",
        "_cluster.hpp",
        "_cluster.cpp",
        "_namespace.hpp",
        "_namespace.cpp",
        "_resource.hpp",
        "kube_wrap.h",
        "kube_wrap.a",
    ],
    hdrs = ["kube.hpp"],
    visibility = ["//visibility:public"],
)
