cc_library(
    name = "kube",
    srcs = glob([
        "*.cc",
        "*.cpp",
        "*.a",
    ]),
    hdrs = glob([
        "*.h",
        "*.hpp",
    ]),
    visibility = ["//visibility:public"],
)